parameters:
  name: ""
  path: ""
  restore: false
  lint: false
  build: false
  test: false
  clean: false
  publish: false
  testResults: "**/results.xml"

steps:
- ${{ if eq(parameters.restore, true) }}:
  - task: Npm@1
    displayName: Restore packages
    inputs:
      workingDir: ${{ parameters.path }}/${{ parameters.name }}

- ${{ if eq(parameters.lint, true) }}:
  - task: Npm@1
    displayName: Run lint
    inputs:
      command: custom
      workingDir: ${{ parameters.path }}/${{ parameters.name }}
      customCommand: run lint

- ${{ if eq(parameters.build, true) }}:
  - task: Npm@1
    displayName: Run build
    inputs:
      command: custom
      workingDir: ${{ parameters.path }}/${{ parameters.name }}
      customCommand: run build

- ${{ if eq(parameters.test, true) }}:
  - task: Npm@1
    displayName: Run tests
    inputs:
      command: custom
      workingDir: ${{ parameters.path }}/${{ parameters.name }}
      customCommand: run test

- ${{ if eq(parameters.clean, true) }}:
  - task: Npm@1
    displayName: Run clean
    inputs:
      command: custom
      workingDir: ${{ parameters.path }}/${{ parameters.name }}
      customCommand: run clean

- ${{ if eq(parameters.test, true) }}:
  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFiles: ${{ parameters.testResults }}
    condition: always()

- ${{ if eq(parameters.publish, true) }}:
  - publish: ${{ parameters.path }}/${{ parameters.name }}
    displayName: Publish artifact
    artifact: ${{ parameters.name }}
