jobs:
- job: OrchestratorV2
  workspace:
    clean: all
  steps:
    - task: releaseorchestrator@2
      displayName: Create release (auto)
      inputs:
        projectName: HelloYo
        definitionName: HelloYo-V2
        releaseStrategy: create
