jobs:
- job: OrchestratorV3
  workspace:
    clean: all
  steps:
    - task: releaseorchestrator@3
      displayName: New release (auto)
      inputs:
        projectName: HelloYo
        definitionName: HelloYo-release
        strategy: new
        stages: DEV,TEST,PROD
