jobs:
- job: Cleanup
  workspace:
    clean: all
  steps:
    - task: PowerShell@2
      displayName: Cleanup releases
      inputs:
        targetType: filePath
        filePath: scripts/Clear-Releases.ps1
        arguments: >
          -OrganizationName dmitryserbin
          -ProjectName HelloYo
          -DefinitionName HelloYo-V2
          -AccessToken $(System.AccessToken)
        pwsh: true
