jobs:
- job: OrchestratorV3
  workspace:
    clean: all
  steps:
  - template: steps/test-v3.yml
    parameters:
      projectName: HelloYo
      definitionName: HelloYo-release
      stages: DEV,TEST,PROD
