jobs:
- job: Cleanup
  workspace:
    clean: all
  steps:
  - template: steps/test-cleanup.yml
    parameters:
      organizationName: dmitryserbin
      projectName: HelloYo
      definitionName: HelloYo-V2
      accessToken: $(System.AccessToken)
