parameters:
  taskV2: false
  taskV3: false
  extension: false

jobs:
- ${{ if eq(parameters.taskV2, true) }}:
  - job: OrchestratorV2
    workspace:
      clean: all
    variables:
    - template: variables.yml
    steps:
    - template: steps/build.yml
      parameters:
        name: ${{ variables.taskNameV2 }}
        path: ${{ variables.tasksPath }}
        restore: true
        lint: true
        build: true
        test: true
        clean: true
        publish: true

- ${{ if eq(parameters.taskV3, true) }}:
  - job: OrchestratorV3
    workspace:
      clean: all
    variables:
    - template: variables.yml
    steps:
    - template: steps/build.yml
      parameters:
        name: ${{ variables.taskNameV3 }}
        path: ${{ variables.tasksPath }}
        restore: true
        lint: true
        build: true
        test: true
        clean: true
        publish: true

- ${{ if eq(parameters.extension, true) }}:
  - job: Extension
    workspace:
      clean: all
    variables:
    - template: variables.yml
    dependsOn:
    - ${{ if eq(parameters.taskV2, true) }}:
      - OrchestratorV2
    - ${{ if eq(parameters.taskV3, true) }}:
      - OrchestratorV3
    steps:
    - template: steps/package.yml
      parameters:
        path: ${{ variables.artifactsPath }}
        contents: |
          docs/**
          images/**
          LICENSE
          *.md
          *.json
        version: ${{ variables.extensionVersion }}
        publish: true
