trigger: none

jobs:
- job: OrchestratorV1
  pool:
    vmImage: windows-latest
  steps:

  - task: CopyFiles@2
    displayName: Copy task
    inputs:
      contents: "**/OrchestratorV1"
      targetFolder: $(Build.ArtifactStagingDirectory)

- job: OrchestratorV2
  pool:
    vmImage: windows-latest
  steps:

  - task: CopyFiles@2
    displayName: Copy task
    inputs:
      contents: "**/OrchestratorV2"
      targetFolder: $(Build.ArtifactStagingDirectory)

- job: Publish
  pool:
    vmImage: windows-latest
  dependsOn:
  - OrchestratorV1
  - OrchestratorV2
  steps:
  - task: CopyFiles@2
    displayName: Copy extension
    inputs:
      contents: |
        LICENSE
        **/Images
        *.md
        *.json
      targetFolder: $(Build.ArtifactStagingDirectory)

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: ReleaseOrchestrator

  - powershell: tree /F
  - powershell: tree /F $(Build.ArtifactStagingDirectory)
  - powershell: tree /F $(System.ArtifactsDirectory)
