trigger: none

variables:
  extensionDirectory: $(Build.ArtifactStagingDirectory)

jobs:
- job: OrchestratorV1
  pool:
    vmImage: windows-latest
  steps:
  - template: template.yml
    parameters:
      name: OrchestratorV1
      path: OrchestratorV1
      restore: false
      build: false
      test: false
      clean: false
      publish: true

- job: OrchestratorV2
  pool:
    vmImage: windows-latest
  steps:
  - template: template.yml
    parameters:
      name: OrchestratorV2
      path: OrchestratorV2
      restore: false
      lint: false
      build: false
      test: false
      clean: false
      publish: true

- job: Extension
  pool:
    vmImage: windows-latest
  dependsOn:
  - OrchestratorV1
  - OrchestratorV2
  steps:
  - task: TfxInstaller@3
    displayName: Use TFX CLI

  - task: CopyFiles@2
    displayName: Copy extension
    inputs:
      contents: |
        Images/**
        LICENSE
        *.md
        *.json
      targetFolder: ${{ variables.extensionDirectory }}

  - task: DownloadPipelineArtifact@2
    displayName: Copy tasks
    inputs:
      source: current
      path: ${{ variables.extensionDirectory }}

  - task: PackageAzureDevOpsExtension@3
    displayName: Package extension
    inputs:
      rootFolder: ${{ variables.extensionDirectory }}
      outputVariable: extensionPath

  - publish: $(extensionPath)
    displayName: Publish artifact
    artifact: Extension
