trigger: none

variables:
  extensionDirectory: $(Build.ArtifactStagingDirectory)

jobs:
- job: OrchestratorV1
  pool:
    vmImage: windows-latest
  steps:
  - template: template.yml
    parameters:
      name: OrchestratorV1

- job: OrchestratorV2
  pool:
    vmImage: windows-latest
  steps:

  - task: Npm@1
    displayName: Restore packages
    inputs:
      workingDir: OrchestratorV2

  - task: Npm@1
    displayName: Run lint
    inputs:
      command: custom
      workingDir: OrchestratorV2
      customCommand: run lint

  - task: Npm@1
    displayName: Run build
    inputs:
      command: custom
      workingDir: OrchestratorV2
      customCommand: run build

  - task: Npm@1
    displayName: Run tests
    inputs:
      command: custom
      workingDir: OrchestratorV2
      customCommand: run test

  - task: Npm@1
    displayName: Run clean
    inputs:
      command: custom
      workingDir: OrchestratorV2
      customCommand: run clean

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFiles: "**/results.xml"

  - publish: OrchestratorV2
    displayName: Publish task
    artifact: OrchestratorV2

- job: Extension
  pool:
    vmImage: windows-latest
  dependsOn:
  - OrchestratorV1
  - OrchestratorV2
  steps:

  - task: DownloadPipelineArtifact@2
    displayName: Download tasks
    inputs:
      source: current
      path: ${{ variables.extensionDirectory }}

  - task: CopyFiles@2
    displayName: Copy extension
    inputs:
      contents: |
        Images/**
        LICENSE
        *.md
        *.json
      targetFolder: ${{ variables.extensionDirectory }}

  - publish: ${{ variables.extensionDirectory }}
    displayName: Publish extension
    artifact: ReleaseOrchestrator
