queue:
  name: Hosted VS2017
  demands: npm

steps:
- task: Npm@1
  displayName: Restore packages
  inputs:
    workingDir: OrchestratorV1

- task: Npm@1
  displayName: Run lint
  inputs:
    command: custom
    workingDir: OrchestratorV1
    customCommand: run lint

- task: Npm@1
  displayName: Run build
  inputs:
    command: custom
    workingDir: OrchestratorV1
    customCommand: run build

- task: Npm@1
  displayName: Run tests
  inputs:
    command: custom
    workingDir: OrchestratorV1
    customCommand: run test

- task: Npm@1
  displayName: Run clean
  inputs:
    command: custom
    workingDir: OrchestratorV1
    customCommand: run clean

- task: PublishTestResults@2
  displayName: Publish test results
  inputs:
    testResultsFiles: "**/results.xml"

- powershell: '@(".git", ".vscode", "*.yaml", "OrchestratorV1\tests") | ForEach-Object { Remove-Item -Path $_ -Force -Recurse -ErrorAction SilentlyContinue }'
  displayName: Clean artifact

- task: PublishBuildArtifacts@1
  displayName: Publish artifact
  inputs:
    PathtoPublish: $(Build.SourcesDirectory)
    ArtifactName: ReleaseOrchestrator
