trigger: none

jobs:
- job: OrchestratorV1
  pool:
    vmImage: windows-latest
  steps:

  - task: CopyFiles@2
    displayName: Copy task
    inputs:
      contents: "OrchestratorV1/**"
      targetFolder: $(Build.ArtifactsDirectory)/OrchestratorV1

- job: OrchestratorV2
  pool:
    vmImage: windows-latest
  steps:

  - task: CopyFiles@2
    displayName: Copy task
    inputs:
      contents: "OrchestratorV2/**"
      targetFolder: $(Build.ArtifactsDirectory)/OrchestratorV2

- job: Extension
  pool:
    vmImage: windows-latest
  dependsOn:
  - OrchestratorV1
  - OrchestratorV2
  steps:
  - task: CopyFiles@2
    displayName: Copy extension
    inputs:
      contents: |
        LICENSE
        Images
        *.md
        *.json
      targetFolder: $(Build.ArtifactsDirectory)

  - powershell: tree /F
  - powershell: tree /F $(System.ArtifactsDirectory)
