trigger: none

jobs:
- job: OrchestratorV1
  pool:
    vmImage: windows-latest
  steps:
  - task: PublishBuildArtifacts@1
    displayName: Publish task
    inputs:
      pathToPublish: OrchestratorV1
      artifactName: OrchestratorV1

- job: OrchestratorV2
  pool:
    vmImage: windows-latest
  steps:
  - task: PublishBuildArtifacts@1
    displayName: Publish task
    inputs:
      pathToPublish: OrchestratorV2
      artifactName: OrchestratorV2

- job: Extension
  pool:
    vmImage: windows-latest
  dependsOn:
  - OrchestratorV1
  - OrchestratorV2
  steps:
  - task: CopyFiles@2
    displayName: Copy extension
    inputs:
      contents: |
        LICENSE
        Images/*
        *.md
        *.json
      targetFolder: $(Build.ArtifactsDirectory)
  - task: DownloadBuildArtifacts@0
    displayName: Copy OrchestratorV1
    inputs:
      downloadType: single
      artifactName: OrchestratorV1
      downloadPath: $(System.ArtifactsDirectory)
  - task: DownloadBuildArtifacts@0
    displayName: Copy OrchestratorV2
    inputs:
      downloadType: single
      artifactName: OrchestratorV2
      downloadPath: $(System.ArtifactsDirectory)
  - powershell: tree /F $(System.ArtifactsDirectory)
  - publish: $(System.ArtifactsDirectory)
    displayName: Publish extension
    artifact: Release Orchestrator
