trigger: none

jobs:
- job: OrchestratorV1
  pool:
    name: Hosted VS2017
    demands: npm
  steps:
  - task: Npm@1
    displayName: Restore packages (V1)
    inputs:
      workingDir: OrchestratorV1

  - task: Npm@1
    displayName: Run build (V1)
    inputs:
      command: custom
      workingDir: OrchestratorV1
      customCommand: run build

  - task: Npm@1
    displayName: Run tests (V1)
    inputs:
      command: custom
      workingDir: OrchestratorV1
      customCommand: run test

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFiles: "**/results.xml"

- job: OrchestratorV2
  steps:
  - task: Npm@1
    displayName: Restore packages
    inputs:
      workingDir: OrchestratorV2

  - task: Npm@1
    displayName: Run lint
    inputs:
      command: custom
      workingDir: OrchestratorV2
      customCommand: run lint

  - task: Npm@1
    displayName: Run build
    inputs:
      command: custom
      workingDir: OrchestratorV2
      customCommand: run build

  - task: Npm@1
    displayName: Run tests
    inputs:
      command: custom
      workingDir: OrchestratorV2
      customCommand: run test

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFiles: "**/results.xml"
