trigger: none

jobs:
- job: OrchestratorV1
  pool:
    vmImage: windows-latest
  steps:
  - task: Npm@1
    displayName: Restore packages
    inputs:
      workingDir: OrchestratorV1

  - task: Npm@1
    displayName: Run build
    inputs:
      command: custom
      workingDir: OrchestratorV1
      customCommand: run build

  - task: Npm@1
    displayName: Run tests
    inputs:
      command: custom
      workingDir: OrchestratorV1
      customCommand: run test

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFiles: "**/results.xml"

  - publish: $(System.DefaultWorkingDirectory)/OrchestratorV1
    artifact: OrchestratorV1

- job: OrchestratorV2
  pool:
    vmImage: windows-latest
  steps:
  - task: Npm@1
    displayName: Restore packages
    inputs:
      workingDir: OrchestratorV2

  - task: Npm@1
    displayName: Run lint
    inputs:
      command: custom
      workingDir: OrchestratorV2
      customCommand: run lint

  - task: Npm@1
    displayName: Run build
    inputs:
      command: custom
      workingDir: OrchestratorV2
      customCommand: run build

  - task: Npm@1
    displayName: Run tests
    inputs:
      command: custom
      workingDir: OrchestratorV2
      customCommand: run test

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFiles: "**/results.xml"

  - publish: $(System.DefaultWorkingDirectory)/OrchestratorV2
    artifact: OrchestratorV2

- job: OrchestratorV2
  pool:
    vmImage: windows-latest
  steps:
  - powershell: tree /F
    displayName: Clean artifact
