trigger: none

variables:
  extensionDirectory: $(Build.ArtifactStagingDirectory)

jobs:
- job: OrchestratorV1
  pool:
    vmImage: windows-latest
  steps:
  - template: template.yml
    parameters:
      name: OrchestratorV1
      path: OrchestratorV1
      restore: true
      build: true
      test: true
      clean: true
      publish: true

- job: OrchestratorV2
  pool:
    vmImage: windows-latest
  steps:
  - template: template.yml
    parameters:
      name: OrchestratorV2
      path: OrchestratorV2
      restore: true
      lint: true
      build: true
      test: true
      clean: true
      publish: true

- job: Extension
  pool:
    vmImage: windows-latest
  dependsOn:
  - OrchestratorV1
  - OrchestratorV2
  steps:
  - task: DownloadPipelineArtifact@2
    displayName: Download tasks
    inputs:
      source: current
      path: ${{ variables.extensionDirectory }}

  - task: CopyFiles@2
    displayName: Copy extension
    inputs:
      contents: |
        Images/**
        LICENSE
        *.md
        *.json
      targetFolder: ${{ variables.extensionDirectory }}

  - publish: ${{ variables.extensionDirectory }}
    displayName: Publish extension
    artifact: ReleaseOrchestrator
