trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Tasks/*

pr: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - template: templates/build.yml
    parameters:
      taskV2: true
      taskV3: true
      extension: true

- stage: Preview
  dependsOn:
  - Build
  jobs:
  - template: templates/preview.yml
    parameters:
      environmentName: Marketplace

- stage: Release
  dependsOn:
  - Build
  - Preview
  jobs:
  - template: templates/release.yml
    parameters:
      environmentName: Marketplace
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
