trigger:
- master

name: $(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)

variables:
  extensionDirectory: $(Build.ArtifactStagingDirectory)

stages:
- stage: Build
  jobs:
  - job: OrchestratorV1
    pool:
      vmImage: windows-latest
    steps:
    - template: template.yml
      parameters:
        name: OrchestratorV1
        path: OrchestratorV1
        restore: true
        build: true
        test: true
        clean: true
        publish: true

  - job: OrchestratorV2
    pool:
      vmImage: windows-latest
    steps:
    - template: template.yml
      parameters:
        name: OrchestratorV2
        path: OrchestratorV2
        restore: true
        lint: true
        build: true
        test: true
        clean: true
        publish: true

  - job: Extension
    pool:
      vmImage: windows-latest
    dependsOn:
    - OrchestratorV1
    - OrchestratorV2
    steps:
    - task: TfxInstaller@3
      displayName: Use TFX CLI

    - task: CopyFiles@2
      displayName: Copy extension
      inputs:
        contents: |
          Images/**
          LICENSE
          *.md
          *.json
        targetFolder: ${{ variables.extensionDirectory }}

    - task: DownloadPipelineArtifact@2
      displayName: Copy tasks
      inputs:
        source: current
        path: ${{ variables.extensionDirectory }}

    - task: PowerShell@2
      displayName: Validate extension
      inputs:
        targetType: filePath
        filePath: CI/validate.ps1
        arguments: -Path ${{ variables.extensionDirectory }} -Required
        pwsh: true

    - task: PackageAzureDevOpsExtension@3
      displayName: Package extension
      inputs:
        rootFolder: ${{ variables.extensionDirectory }}
        outputVariable: extensionPath

    - publish: $(extensionPath)
      displayName: Publish artifact
      artifact: Extension

- stage: Test
  jobs:
  - job: Install
    pool:
      vmImage: windows-latest
    steps:
    - download: current
      displayName: Download artifacts

    - task: taskpublisher@1
      displayName: Install OrchestratorV1
      inputs:
        ConnectedService: dmitryserbin.tasks
        TaskPath: $(Pipeline.Workspace)/OrchestratorV1
        Replace: true

    - task: taskpublisher@1
      displayName: Install OrchestratorV2
      inputs:
        ConnectedService: dmitryserbin.tasks
        TaskPath: $(Pipeline.Workspace)/OrchestratorV2
        Replace: false

  - job: OrchestratorV1
    pool:
      vmImage: windows-latest
    dependsOn:
    - Install
    variables:
      projectId: 761623f0-c4c0-4dab-884b-a428a01c200f
      definitionId: 1
      releaseId: 162
      releaseStages: DEV,TEST,PROD
    steps:
    - task: releaseorchestrator@1
      displayName: Specific Release (Manual)
      inputs:
        TargetProject: ${{ variables.projectId }}
        TargetDefinition: ${{ variables.definitionId }}
        ReleaseStrategy: specific
        TargetRelease: ${{ variables.releaseId }}
        TargetReleaseStages: ${{ variables.releaseStages }}

    - task: releaseorchestrator@1
      displayName: Create Release (Auto)
      inputs:
        TargetProject: ${{ variables.projectId }}
        TargetDefinition: ${{ variables.definitionId }}

    - task: releaseorchestrator@1
      displayName: Latest Release (Manual)
      inputs:
        TargetProject: ${{ variables.projectId }}
        TargetDefinition: ${{ variables.definitionId }}
        ReleaseStrategy: latest
        TargetReleaseStages: ${{ variables.releaseStages }}

  - job: OrchestratorV2
    dependsOn:
    - Install
    pool:
      vmImage: windows-latest
    variables:
      projectName: HelloYo
      definitionName: HelloYo
      releaseName: HelloYo-20190521.1-1
      releaseStages: DEV,TEST,PROD
    steps:
    - task: releaseorchestrator@2
      displayName: Specific Release (Manual)
      inputs:
        ProjectName: ${{ variables.projectName }}
        DefinitionName: ${{ variables.definitionName }}
        ReleaseStrategy: specific
        ReleaseName: ${{ variables.releaseName }}
        ReleaseStages: ${{ variables.releaseStages }}

    - task: releaseorchestrator@2
      displayName: Create Release (Auto)
      inputs:
        ProjectName: ${{ variables.projectName }}
        DefinitionName: ${{ variables.definitionName }}

    - task: releaseorchestrator@2
      displayName: Latest Release (Manual)
      inputs:
        ProjectName: ${{ variables.projectName }}
        DefinitionName: ${{ variables.definitionName }}
        ReleaseStrategy: latest
        ReleaseStages: ${{ variables.releaseStages }}

- stage: Release
  jobs:
  - deployment: Extension
    pool:
      vmImage: windows-latest
    environment: Marketplace
    strategy:
      runOnce:
        deploy:
          steps:
          - task: TfxInstaller@3
            displayName: Use TFX CLI
