trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Tasks/*

parameters:
- name: testV1
  displayName: Test V1
  type: boolean
  default: true
- name: testV2
  displayName: Test V2
  type: boolean
  default: true
- name: testV3
  displayName: Test V3
  type: boolean
  default: true

stages:
- stage: Build
  jobs:
  - template: templates/build.yml
    parameters:
      taskV1: true
      taskV2: true
      taskV3: true
      extension: true

- stage: Test
  dependsOn:
  - Build
  jobs:
  - template: templates/test.yml
    parameters:
      testV1: ${{ parameters.testV1 }}
      testV2: ${{ parameters.testV2 }}
      testV3: ${{ parameters.testV3 }}
      cleanup: true

- stage: Release
  dependsOn:
  - Build
  - Test
  jobs:
  - template: templates/release.yml
    parameters:
      environmentName: Marketplace
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
