trigger: none

strategy:
  matrix:
    vmImage:
      - ubuntu-latest
      - windows-latest
      - ubuntu-20.04
      - windows-2019

pool:
  vmImage: $(vmImage)

stages:
- stage: OrchestratorV2
  dependsOn: []
  jobs:
    - template: templates/smoke-v2.yml
- stage: OrchestratorV3
  dependsOn: []
  jobs:
    - template: templates/smoke-v3.yml
- stage: Cleanup
  dependsOn:
    - OrchestratorV2
  jobs:
    - template: templates/cleanup-v2.yml
