name: CI

on:
  push:
    branches:
      - main
      - features/upgrade
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - OrchestratorV2
          - OrchestratorV3
    defaults:
      run:
        working-directory: tasks/${{ matrix.name }}
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore packages
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Run clean
        run: npm run clean
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: tasks/${{ matrix.name }}
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          files: tasks/${{ matrix.name }}/tests/*.xml
  package:
    name: Package
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TFX CLI
        run: npm install -g tfx-cli
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extension/tasks
      - name: Copy extension
        run: |
          cp docs/** extension/
          cp images/** extension/
          cp LICENSE extension/
          cp *.md extension/
          cp *.json extension/
      - name: Version extension
        run: |
          pwsh -File ci/scripts/Set-Version.ps1 -Path extension -Patch ${{ github.run_number }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Extension
          path: extension
