name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
  workflow_dispatch:

jobs:
  build-v2:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: tasks/OrchestratorV2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore packages
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Run clean
        run: npm run clean
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          files: tests/*.xml
  build-v3:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: tasks/OrchestratorV3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore packages
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Run clean
        run: npm run clean
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          files: tests/*.xml
  package:
    runs-on: ubuntu-latest
    needs:
      - build-v2
      - build-v3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
