name: CI

on:
  push:
    branches:
      - main
      - features/upgrade
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - OrchestratorV2
          - OrchestratorV3
    defaults:
      run:
        working-directory: tasks/${{ matrix.name }}
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore packages
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Run clean
        run: npm run clean
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            tasks/${{ matrix.name }}
            !tasks/${{ matrix.name }}/**/*.ts
            !tasks/${{ matrix.name }}/tests
            !tasks/${{ matrix.name }}/tsconfig.json
            !tasks/${{ matrix.name }}/*.config.mjs
            !tasks/${{ matrix.name }}/*.svg
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          files: tasks/${{ matrix.name }}/tests/*.xml
  package:
    name: Package
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TFX CLI
        run: npm install -g tfx-cli
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extension/tasks
      - name: Copy extension
        run: |
          mkdir -p extension/images && cp images/** extension/images/
          mkdir -p extension/docs && cp docs/** extension/docs/
          cp LICENSE extension/
          cp *.md extension/
          cp *.json extension/
      - name: Version extension
        run: |
          pwsh -File ci/scripts/Set-Version.ps1 -Path extension -Patch ${{ github.run_number }}${{ github.run_attempt }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Extension
          path: extension
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'Production' || 'Preview' }}
    needs:
      - package
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TFX CLI
        run: npm install -g tfx-cli
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Extension
          path: Extension
      - name: Set private preview
        run: |
          sed -i 's/"galleryFlags": \[\],/"galleryFlags": \["Preview"\],/' Extension/vss-extension.json
          sed -i 's/"public": true,/"public": false,/' Extension/vss-extension.json
        if: ${{ github.ref != 'refs/heads/master' }}
      - name: Package extension
        run: |
          tfx extension create --root Extension
      - name: Validate extension
        run: |
          extensionPath=$(find . -name "*.vsix")
          if [ -z "$extensionPath" ]; then
            echo "No extension found"
            exit 1
          fi
          tfx extension isvalid --publisher dmitryserbin --extension-id release-orchestrator --vsix $extensionPath --token ${{ secrets.MARKETPLACE_TOKEN }}
      # - name: Publish extension
      #   run: |
      #     tfx extension publish --vsix *.vsix --token ${{ secrets.MARKETPLACE_TOKEN }}
      # - name: Share preview extension
      #   run: |
      #     tfx extension share --publisher dmitryserbin --extension-id release-orchestrator --share-with dmitryserbin,iag --token ${{ secrets.MARKETPLACE_TOKEN }}
      #   if: ${{ github.ref != 'refs/heads/master' }}
