name: CI

on:
  push:
    branches:
      - main
      - features/upgrade
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
  workflow_dispatch:

jobs:
  build-v2:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: tasks/OrchestratorV2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore packages
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Run clean
        run: npm run clean
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrchestratorV2
          path: tasks/OrchestratorV2
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          files: tasks/OrchestratorV2/tests/*.xml
  build-v3:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: tasks/OrchestratorV3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore packages
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Run clean
        run: npm run clean
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrchestratorV3
          path: tasks/OrchestratorV3
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          files: tasks/OrchestratorV3/tests/*.xml
  package:
    runs-on: ubuntu-latest
    needs:
      - build-v2
      - build-v3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TFX CLI
        run: npm install -g tfx-cli
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extension/tasks
      - name: Copy extension
        run: |
          cp docs/** extension/
          cp images/** extension/
          cp LICENSE extension/
          cp *.md extension/
          cp *.json extension/
      - name: Version extension
        run: |
          pwsh -File ci/scripts/Set-Version.ps1 -Path extension -Patch ${{ github.run_number }} -UpdateBuildNumber
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Extension
          path: extension
